// GUERRIER — Panneau de combat
// ═══════════════════════════════════════

function renderGuerrier(p) {
  const wsC = p.wildshape;
  const guerrierLvl = ((p.classes||[]).find(c=>c.name==='Guerrier')||{}).level||0;
  if (!guerrierLvl || wsC?.active) return '';
  const lvl = totalLevel(p);
  const forM = mod(p.abilities[0]);
  const dexM = mod(p.abilities[1]);
  const conM = mod(p.abilities[2]);
  const combatStyle = p.combatStyle||'';
  const guerPath = (p.features||[]).find(f=>['Champion','Maître de guerre','Chevalier occulte'].includes(f.name));
  const isChampion = guerPath?.name==='Champion';
  const isMdG = guerPath?.name==='Maître de guerre';
  const isCO = guerPath?.name==='Chevalier occulte';

  return cs('cs-guerrier',`<div class="panel mb10"><div class="pt" style="display:flex;align-items:center;gap:6px"><span class="mj-drag-handle" title="Déplacer">⠿</span>⚔ Guerrier — Capacités</div>
    <div style="margin-bottom:${guerrierLvl>=2?'14':'0'}px">
      <div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">💨 Second souffle</div>
      <div style="font-size:11px;color:var(--text3);margin-bottom:8px">${_featDesc('Guerrier','Second souffle')}</div>
      ${(()=>{const ssUsed=(p.combatCharges||{})['Second souffle']!==undefined?p.combatCharges['Second souffle']:1;return`<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><div style="display:flex;gap:4px"><span class="slot-bubble${ssUsed>0?'':' used'}" onclick="useCombatCharge('Second souffle',1)"></span></div><button class="btn bsm" onclick="rollCustomDmg('1d10+${lvl}','Second souffle')">🎲 1d10+${lvl}</button><button class="btn bsm" onclick="recoverCombatCharge('Second souffle',1)">↺ Repos court</button></div>`;})()}
    </div>
    ${guerrierLvl>=2?(()=>{const saMax=guerrierLvl>=17?2:1;const saUsed=(p.combatCharges||{})['SursautAction']!==undefined?p.combatCharges['SursautAction']:saMax;return`<div style="margin-bottom:${guerrierLvl>=9?'14':'0'}px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">⚡ Sursaut d'action${guerrierLvl>=17?' (×2)':''}</div><div style="font-size:11px;color:var(--text3);margin-bottom:8px">${_featDesc('Guerrier',"Sursaut d'action")}</div><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><div style="display:flex;gap:4px">${Array.from({length:saMax},(_,i)=>`<span class="slot-bubble${i<saUsed?'':' used'}" onclick="useCombatCharge('SursautAction',${saMax})"></span>`).join('')}</div><span style="font-size:10px;color:var(--text3)">${saUsed}/${saMax}</span><button class="btn bsm" onclick="recoverCombatCharge('SursautAction',${saMax})">↺ Repos court</button></div></div>`;})():''}
    ${guerrierLvl>=9?(()=>{const indMax=guerrierLvl>=17?3:(guerrierLvl>=13?2:1);const indUsed=(p.combatCharges||{})['Indomptable']!==undefined?p.combatCharges['Indomptable']:indMax;return`<div><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">🔄 Indomptable${guerrierLvl>=13?` (×${indMax})`:''}</div><div style="font-size:11px;color:var(--text3);margin-bottom:8px">${_featDesc('Guerrier','Indomptable')}</div><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><div style="display:flex;gap:4px">${Array.from({length:indMax},(_,i)=>`<span class="slot-bubble${i<indUsed?'':' used'}" onclick="useCombatCharge('Indomptable',${indMax})"></span>`).join('')}</div><span style="font-size:10px;color:var(--text3)">${indUsed}/${indMax}</span><button class="btn bsm" onclick="recoverCombatCharge('Indomptable',${indMax})">↺ Repos long</button></div></div>`;})():''}
    ${combatStyle?`<div style="margin-top:8px;padding:6px 8px;background:var(--surface2);border-radius:6px;font-size:11px;color:var(--text2)">⚔ Style de combat : <strong>${combatStyle}</strong></div>`:''}
    ${isChampion&&guerrierLvl>=3?`<div style="margin-top:12px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:6px">🏆 Champion</div><div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Critique amélioré (niv.3) — Coup critique sur 19-20</div>${guerrierLvl>=7?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Athlète accompli (niv.7) — ½ maîtrise aux jets FOR/DEX/CON sans maîtrise</div>`:''} ${guerrierLvl>=15?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Critique supérieur (niv.15) — Coup critique sur 18-20</div>`:''} ${guerrierLvl>=18?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:rgba(76,175,80,.07);border:1px solid rgba(76,175,80,.2);border-radius:6px">Survivant (niv.18) — Si PV ≤ ½ max au début de ton tour : récupère <strong style="color:#4caf50">5+${conM}</strong> PV automatiquement</div>`:''}</div>`:''}
    ${isMdG&&guerrierLvl>=3?(()=>{const mdgDiceMax=guerrierLvl>=15?7:guerrierLvl>=10?6:guerrierLvl>=7?5:4;const mdgDie=guerrierLvl>=18?'d12':guerrierLvl>=10?'d10':'d8';const mdgManoevres=guerrierLvl>=15?9:guerrierLvl>=10?7:guerrierLvl>=7?5:3;const mdgUsed=(p.combatCharges||{})['DésSupériorité']!==undefined?p.combatCharges['DésSupériorité']:mdgDiceMax;return`<div style="margin-top:12px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:6px">⚔ Maître de guerre</div><div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;flex-wrap:wrap"><div class="sb hi" style="padding:4px 12px;flex-shrink:0"><div class="sn">Dé</div><div style="font-size:16px;font-weight:700;color:var(--cp)">${mdgDie}</div></div><div class="sb" style="padding:4px 12px;flex-shrink:0"><div class="sn">Manœuvres</div><div style="font-size:16px;font-weight:700;color:var(--cp)">${mdgManoevres}</div></div></div><div style="font-size:11px;color:var(--text3);margin-bottom:4px">Supériorité martiale (DD = ${8+pb(guerrierLvl)+Math.max(forM,dexM)}) :</div><div style="display:flex;gap:4px;flex-wrap:wrap;margin-bottom:4px">${Array.from({length:mdgDiceMax},(_,i)=>`<span class="slot-bubble${i<mdgUsed?'':' used'}" onclick="useCombatCharge('DésSupériorité',${mdgDiceMax})"></span>`).join('')}</div><div style="font-size:10px;color:var(--text3);margin-bottom:6px">${mdgUsed}/${mdgDiceMax} • Repos court</div><div style="display:flex;gap:4px;flex-wrap:wrap"><button class="btn bsm" onclick="rollCustomDmg('1${mdgDie}','Dé de supériorité')">🎲 1${mdgDie}</button><button class="btn bsm" onclick="recoverCombatCharge('DésSupériorité',${mdgDiceMax})">↺ Repos court</button></div>${guerrierLvl>=7?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-top:6px">Observation de l'ennemi (niv.7) — 1 min à observer : savoir si une cible est inférieure/égale/supérieure en FOR</div>`:''} ${guerrierLvl>=15?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-top:4px">Implacable (niv.15) — Si à 0 dés au début de l'initiative, récupère 1 dé de supériorité</div>`:''}</div>`;})():''}
    ${isCO&&guerrierLvl>=3?`<div style="margin-top:12px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:6px">🔮 Chevalier occulte</div><div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Sorts de magicien (INT), abjuration/évocation. Lien d'arme (niv.3) — action bonus : invoquer ou rappeler l'arme liée</div>${guerrierLvl>=7?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Magie de guerre (niv.7) — Quand tu lances un cantrip, tu peux effectuer 1 attaque en action bonus</div>`:''} ${guerrierLvl>=10?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Frappe occulte (niv.10) — Si tu touches une créature, elle a désavantage à son prochain JS contre un de tes sorts ce tour</div>`:''} ${guerrierLvl>=15?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Charge arcanique (niv.15) — Quand tu utilises Sursaut d'action, tu peux te téléporter jusqu'à 9m</div>`:''} ${guerrierLvl>=18?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px">Magie de guerre améliorée (niv.18) — L'attaque bonus s'applique à n'importe quel sort, pas seulement les cantrieps</div>`:''}</div>`:''}
  </div>`);
}
