// MOINE — Panneau de combat + actions
// ═══════════════════════════════════════

function renderMoine(p) {
  const wsC = p.wildshape;
  const moineLvl = ((p.classes||[]).find(c=>c.name==='Moine')||{}).level||0;
  if (!moineLvl || wsC?.active) return '';
  const lvl = totalLevel(p);
  const forM = mod(p.abilities[0]);
  const dexM = mod(p.abilities[1]);
  const sagM = mod(p.abilities[4]);
  const moinePath = (p.features||[]).find(f=>["Voie de la paume","Voie de l'ombre",'Voie des quatre éléments'].includes(f.name));
  const isPaume = moinePath?.name==='Voie de la paume';
  const isOmbre = moinePath?.name==="Voie de l'ombre";
  const isQE = moinePath?.name==='Voie des quatre éléments';
  const kiMax = moineLvl;
  const artsMartiauxDie = moineLvl>=17?'d10':moineLvl>=11?'d8':moineLvl>=5?'d6':'d4';

  return cs('cs-moine',`<div class="panel mb10"><div class="pt" style="display:flex;align-items:center;gap:6px"><span class="mj-drag-handle" title="Déplacer">⠿</span>☯ Moine — Capacités</div>
      <div style="margin-bottom:12px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:4px">👊 Arts martiaux</div>
        <div style="font-size:13px;color:var(--text3);margin-bottom:6px">Frappe à mains nues ou arme moine — utilise FOR ou DEX au choix. Dé de base à ce niveau :</div>
        <div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">
          <div class="sb hi" style="padding:6px 14px;flex-shrink:0"><div class="sn">Dé</div><div style="font-size:15px;font-weight:700;color:var(--cp)">${artsMartiauxDie}</div></div>
          <div><button class="btn bsm" onclick="rollCustomDmg('1${artsMartiauxDie}+${Math.max(forM,dexM)}','Arts martiaux')">🎲 1${artsMartiauxDie}${fmt(Math.max(forM,dexM))} dégâts</button>
          <div style="font-size:12px;color:var(--text3);margin-top:3px">Action bonus : 1 frappe supplémentaire (sans ki)</div></div>
        </div>
        ${!(p.equip||{}).chest?.name?`<div style="margin-top:8px;padding:6px 10px;background:var(--surface2);border-radius:2px;font-size:13px;color:var(--text3)">🛡 Défense sans armure (sans armure) : CA = 10 + DEX (${fmt(dexM)}) + SAG (${fmt(sagM)}) = <strong style="color:var(--cp)">${10+dexM+sagM}</strong></div>`:''}
      </div>
      ${moineLvl>=2?(()=>{const remaining=(p.combatCharges?.['Ki']!==undefined)?p.combatCharges['Ki']:kiMax;return`<div style="border-top:1px solid var(--border);padding-top:10px;margin-bottom:10px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:4px">☯ Points de ki — ${kiMax} / récup. repos court</div><div style="font-size:13px;color:var(--text3);margin-bottom:8px">Points dépensés pour activer des techniques de moine. Coût : 1 à plusieurs ki selon la technique.</div><div style="display:flex;gap:4px;flex-wrap:wrap;margin-bottom:6px">${Array.from({length:kiMax},(_,ki)=>`<span class="slot-bubble${ki<remaining?'':' used'}" onclick="toggleKi(${ki},${kiMax})" style="cursor:pointer" title="${ki<remaining?'Cliquer pour dépenser 1 ki':'ki dépensé'}"></span>`).join('')}</div><div style="display:flex;align-items:center;gap:8px"><span style="font-size:13px;color:var(--text3)">${remaining}/${kiMax} disponibles</span><button class="btn bsm" onclick="P().combatCharges=P().combatCharges||{};P().combatCharges['Ki']=${kiMax};_markUnsaved();render()">↺ Repos court</button></div></div>`;})():''}
      <div style="border-top:1px solid var(--border);padding-top:10px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:8px">Techniques disponibles</div>
        ${moineLvl>=2?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">🌊 Déluge de coups <span style="font-size:12px;color:var(--cp);margin-left:4px">🔸 1 ki</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px">Action bonus : effectue 2 frappes à mains nues supplémentaires après l'action Attaquer.</div></div>`:''}
        ${moineLvl>=2?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">🧘 Défense patiente <span style="font-size:12px;color:var(--cp);margin-left:4px">🔸 1 ki</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px">Action bonus : utilise l'action Esquiver.</div></div>`:''}
        ${moineLvl>=2?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">💨 Déplacement aérien <span style="font-size:12px;color:var(--cp);margin-left:4px">🔸 1 ki</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px">Action bonus : Se désengager OU Foncer ; ta distance de saut est doublée pour le tour.</div></div>`:''}
        ${moineLvl>=3?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">🛡 Parade de projectiles <span style="font-size:12px;color:var(--cp);margin-left:4px">↪ Réaction</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px;margin-bottom:6px">Réaction : réduis les dégâts d'un projectile de <strong>1d10+${dexM+moineLvl}</strong> (DEX+niveau).</div><div style="display:flex;gap:4px;flex-wrap:wrap;margin-bottom:6px"><button class="btn bsm" onclick="(()=>{const r=Math.ceil(Math.random()*10)+${dexM+moineLvl};showToast('↪ Parade : réduit de <strong>'+r+'</strong> dégâts',2500);})()">↪ Lancer réduction</button></div><div style="font-size:12px;color:var(--warn);margin-bottom:4px">Si réduit à 0 — dépense 1 ki : renvoie le projectile (portée 18m, att. +${pb(lvl)+dexM}, dégâts ${artsMartiauxDie}+${dexM})</div><button class="btn bsm" style="color:var(--warn);border-color:var(--warn)" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};const ki=(p.combatCharges['Ki']!==undefined)?p.combatCharges['Ki']:${kiMax};if(ki<1){showToast('❌ Plus de ki !');return;}p.combatCharges['Ki']=ki-1;const r=Math.ceil(Math.random()*${artsMartiauxDie.slice(1)})+${dexM};_markUnsaved();render();showToast('🎯 Renvoyer : att. +${pb(lvl)+dexM} — dégâts <strong>'+r+'</strong> (${artsMartiauxDie}+${dexM})',3000);})()">🎯 Renvoyer (−1 ki)</button></div>`:''}
        ${moineLvl<2?`<div style="font-size:13px;color:var(--text3);font-style:italic;padding:4px 0">Ki et techniques disponibles à partir du niveau 2.</div>`:''}
        ${moineLvl>=4?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">🪂 Chute ralentie <span style="font-size:12px;color:var(--cp);margin-left:4px">↪ Réaction</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px">Quand tu tombes : réduis les dégâts de chute de <strong>${5*moineLvl}</strong> (5 × niveau de moine).</div></div>`:''}
        ${moineLvl>=5?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">⚡ Frappe étourdissante <span style="font-size:12px;color:var(--cp);margin-left:4px">1 ki</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px">Lors d'une attaque au corps à corps qui touche : la cible doit réussir un JS CON (DD ${8+pb(lvl)+sagM}) ou est étourdie jusqu'à la fin de ton prochain tour.</div></div>`:''}
        ${moineLvl>=6?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">✨ Frappes de ki <span style="font-size:12px;color:var(--text3);margin-left:4px">passif</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px">Tes attaques à mains nues comptent comme magiques (contournent les résistances/immunités au non-magique).</div></div>`:''}
        ${moineLvl>=7?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">🌀 Esquive totale <span style="font-size:12px;color:var(--text3);margin-left:4px">passif</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px">Effet à JS DEX pour moitié des dégâts : réussite = <strong>aucun</strong> dégât, échec = moitié.</div></div>`:''}
        ${moineLvl>=7?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">🧘 Sérénité</div><div style="font-size:13px;color:var(--text3);margin-top:2px">Action : mets fin à un effet qui te rend <strong>charmé</strong> ou <strong>effrayé</strong>.</div></div>`:''}

        ${moineLvl>=9?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">⚡ Pas comme l'éclair <span style="font-size:12px;color:var(--cp);margin-left:4px">🔸 2 ki</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px">Action bonus : téléporte-toi jusqu'à 18m vers un espace libre que tu vois.</div></div>`:''}
        ${isPaume&&moineLvl>=17?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">☠ Frappe des vibrations <span style="font-size:12px;color:var(--cp);margin-left:4px">3 ki</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px">Lors d'une attaque qui touche : vibrations imperceptibles pendant ${moineLvl} jours. Action pour les déclencher : JS CON (DD ${8+pb(lvl)+sagM}) — échec : la cible tombe à 0 PV ; réussite : 10d10 dégâts nécrotiques.</div></div>`:''}
        ${moineLvl>=18?`<div style="padding:7px 10px;background:var(--surface2);border-radius:2px;margin-bottom:6px"><div style="font-size:13px;font-weight:600">👻 Désertion de l'âme <span style="font-size:12px;color:var(--cp);margin-left:4px">4 ki</span></div><div style="font-size:13px;color:var(--text3);margin-top:2px">Action : invisible 1 minute + résistance à tous les dégâts sauf force. Ou <strong>8 ki</strong> : lancer <em>projection astrale</em> (sans composantes, toi seul).</div></div>`:''}
      </div>
      ${isPaume&&moineLvl>=3?`<div style="margin-top:12px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:6px">🥋 Voie de la paume</div><div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Technique de la paume (niv.3) — Quand tu touches avec Déluge de coups : pousser 4,5m / faire tomber / priver de réaction (au choix)</div>${moineLvl>=6?(()=>{const ppUsed=!!(p.combatCharges||{})['PlénitudePhysiqueUsed'];return`<div style="padding:6px 8px;background:${ppUsed?'rgba(200,168,75,.08)':'var(--surface2)'};border:1px solid ${ppUsed?'var(--cp)':'var(--border)'};border-radius:2px;margin-bottom:4px"><div style="font-size:13px;font-weight:600;color:var(--text2)">Plénitude physique (niv.6) — 1×/repos long</div><div style="font-size:12px;color:var(--text3);margin:2px 0">Action : récupère ${moineLvl*3} PV (niveau × 3)</div>${ppUsed?`<button class="btn bsm" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};delete p.combatCharges['PlénitudePhysiqueUsed'];saveAll();render();})()">↺ Repos long</button>`:`<button class="btn bsm" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};p.combatCharges['PlénitudePhysiqueUsed']=true;p.hp=Math.min(p.hpMax||(p.hp||0),p.hp+${moineLvl*3});saveAll();render();showToast('💚 +${moineLvl*3} PV (Plénitude physique)');})()">⚡ Soigner (+${moineLvl*3} PV)</button>`}</div>`;})():''}${moineLvl>=11?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px">Tranquillité (niv.11) — Après un repos long, bénéfice de Sanctuaire (DD ${8+pb(moineLvl)+sagM}) jusqu'au prochain tour de combat</div>`:''}</div>`:''}
      ${isOmbre&&moineLvl>=3?`<div style="margin-top:12px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:6px">🌑 Voie de l'ombre</div><div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Arts des ombres (niv.3) — 2 ki : lancer ténèbres, vision dans le noir, passage sans trace ou silence. Illusion mineure gratuite en tout temps.</div>${moineLvl>=6?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Foulée d'ombre (niv.6) — Action bonus : téléportation 18m dans un espace en pénombre ou ténèbres. Avantage sur la prochaine attaque.</div>`:''} ${moineLvl>=11?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Linceul d'ombre (niv.11) — Action : devenir invisible en pénombre/ténèbres (jusqu'au début de ton prochain tour)</div>`:''} ${moineLvl>=17?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px">Opportuniste (niv.17) — Réaction : quand une créature à 1,5m est touchée par un allié, tu peux faire 1 attaque contre elle</div>`:''}</div>`:''}
      ${isQE&&moineLvl>=3?(()=>{const dd=8+pb(moineLvl)+sagM;const _ki=(p.combatCharges?.['Ki']!==undefined)?p.combatCharges['Ki']:kiMax;const disc=[
        {n:'Harmonie élémentaire',ki:0,lvl:3,d:'Manipulation mineure d\'un élément (effet sensoriel, comme un cantrip).'},
        {n:'Crocs du serpent de feu',ki:1,lvl:3,d:'Ton corps-à-corps gagne +1d10 feu ce tour + pousse la cible de 1,5m.',roll:'1d10'},
        {n:'Onde de choc (4 tonnerres)',ki:1,lvl:3,d:`Cube 4,5m, JS CON DD ${dd} : 2d8 tonnerre + repoussé.`,roll:'2d8'},
        {n:'Cendres balayantes',ki:1,lvl:3,d:`Cône 4,5m, JS DEX DD ${dd} : 3d6 feu.`,roll:'3d6'},
        {n:'Fouet d\'eau',ki:1,lvl:3,d:`JS DEX DD ${dd} : 3d10 contondant + cible attirée 7,5m ou à terre.`,roll:'3d10'},
        {n:'Poing d\'air invaincu',ki:1,lvl:3,d:`JS FOR DD ${dd} : 3d10 contondant + repoussé 6m + à terre.`,roll:'3d10'},
        {n:'Ruée des esprits du vent',ki:1,lvl:3,d:'Souffle de vent puissant (ligne de 18m).'},
        {n:'Étreinte du vent du nord',ki:2,lvl:6,d:`Immobilisation de personne — JS SAG DD ${dd}.`},
        {n:'Gong du sommet',ki:2,lvl:6,d:`Fracassement — 3d8 tonnerre, JS CON DD ${dd}.`,roll:'3d8'},
        {n:'Flammes du phénix',ki:3,lvl:11,d:`Boule de feu — 8d6 feu, JS DEX DD ${dd}.`,roll:'8d6'},
        {n:'Souffle de l\'hiver',ki:5,lvl:17,d:`Cône de froid — 8d8 froid, JS CON DD ${dd}.`,roll:'8d8'},
      ].filter(x=>moineLvl>=x.lvl);return`<div style="margin-top:12px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:6px">🌊 Voie des quatre éléments — Disciplines</div><div style="font-size:12px;color:var(--text3);margin-bottom:6px">DD ${dd} · coûts maison (−1 ki) · ${_ki}/${kiMax} ki. Tu connais 1 discipline (niv.3) +1 aux niv.6/11/17 — n'utilise que celles que tu as choisies.</div>${disc.map(x=>`<div style="padding:6px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px"><div style="display:flex;align-items:center;justify-content:space-between;gap:6px"><div style="flex:1"><div style="font-size:13px;font-weight:600">${esc(x.n)} <span style="font-size:12px;color:var(--cp)">${x.ki} ki</span></div><div style="font-size:12px;color:var(--text3)">${esc(x.d)}</div></div><div style="display:flex;gap:3px;flex-shrink:0">${x.roll?`<button class="btn bsm" onclick="rollCustomDmg('${x.roll}','${jsq(x.n)}')">🎲</button>`:''}<button class="btn bsm bac" onclick="_moineSpendKi(${x.ki},'${jsq(x.n)}')">☯ ${x.ki>0?'−'+x.ki:'0'}</button></div></div></div>`).join('')}</div>`;})():''}
      ${moineLvl>=10?`<div style="margin-top:8px;padding:6px 10px;background:var(--surface2);border-radius:2px;font-size:13px;color:var(--text3)">🌿 <strong>Pureté physique</strong> (niv.10) : Immunité aux maladies et aux poisons.</div>`:''}
      ${moineLvl>=14?`<div style="margin-top:6px;padding:6px 10px;background:var(--surface2);border-radius:2px;font-size:13px;color:var(--text3)">💎 <strong>Âme de diamant</strong> (niv.14) : maîtrise de <strong>tous</strong> les jets de sauvegarde, et tu peux <strong>dépenser 1 ki pour relancer</strong> un JS raté (le bouton de relance apparaît sur ton jet de sauvegarde).</div>`:''}
      ${moineLvl>=15?`<div style="margin-top:6px;padding:6px 10px;background:var(--surface2);border-radius:2px;font-size:13px;color:var(--text3)">⏳ <strong>Jeunesse éternelle</strong> (niv.15) : ton ki te sustente — tu ne subis plus les affres de la vieillesse et ne peux plus être vieilli par magie (tu peux encore mourir de vieillesse). Tu n'as plus besoin de manger ni de boire.</div>`:''}
      ${moineLvl>=20?`<div style="margin-top:6px;padding:6px 10px;background:var(--surface2);border-radius:2px;font-size:13px;color:var(--text3)">✨ <strong>Perfection de l'être</strong> (niv.20) : quand tu lances l'initiative sans plus aucun point de ki, tu regagnes <strong>4 points de ki</strong>.</div>`:''}
    </div>`);
}

function toggleKi(idx,max){const p=P();if(!p.combatCharges)p.combatCharges={};const cur=p.combatCharges['Ki']!==undefined?p.combatCharges['Ki']:max;p.combatCharges['Ki']=idx<cur?idx:Math.min(max,idx+1);_markUnsaved();render();}
function _moineSpendKi(cost,name){const p=P();if(!p.combatCharges)p.combatCharges={};const mx=((p.classes||[]).find(c=>c.name==='Moine')||{}).level||0;const cur=p.combatCharges['Ki']!==undefined?p.combatCharges['Ki']:mx;if(cost>0&&cur<cost){showBanner('❌','Pas assez de ki',name+' coûte '+cost+' ki',{variant:'danger'});return;}if(cost>0){p.combatCharges['Ki']=cur-cost;_markUnsaved();render();}showBanner('☯',name,cost>0?'−'+cost+' ki ('+(cur-cost)+' restants)':'Effet mineur (sans ki)',{variant:'info'});}
