// MOINE — Panneau de combat + actions
// ═══════════════════════════════════════

function renderMoine(p) {
  const wsC = p.wildshape;
  const moineLvl = ((p.classes||[]).find(c=>c.name==='Moine')||{}).level||0;
  if (!moineLvl || wsC?.active) return '';
  const lvl = totalLevel(p);
  const forM = mod(p.abilities[0]);
  const dexM = mod(p.abilities[1]);
  const sagM = mod(p.abilities[4]);
  const moinePath = (p.features||[]).find(f=>["Voie de la paume","Voie de l'ombre",'Voie des quatre éléments'].includes(f.name));
  const isPaume = moinePath?.name==='Voie de la paume';
  const isOmbre = moinePath?.name==="Voie de l'ombre";
  const isQE = moinePath?.name==='Voie des quatre éléments';
  const kiMax = moineLvl;
  const artsMartiauxDie = moineLvl>=17?'d10':moineLvl>=11?'d8':moineLvl>=5?'d6':'d4';

  return cs('cs-moine',`<div class="panel mb10"><div class="pt" style="display:flex;align-items:center;gap:6px"><span class="mj-drag-handle" title="Déplacer">⠿</span>☯ Moine — Capacités</div>
      <div style="margin-bottom:12px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">👊 Arts martiaux</div>
        <div style="font-size:11px;color:var(--text3);margin-bottom:6px">Frappe à mains nues ou arme moine — utilise FOR ou DEX au choix. Dé de base à ce niveau :</div>
        <div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap">
          <div class="sb hi" style="padding:6px 14px;flex-shrink:0"><div class="sn">Dé</div><div style="font-size:20px;font-weight:700;color:var(--cp)">${artsMartiauxDie}</div></div>
          <div><button class="btn bsm" onclick="rollCustomDmg('1${artsMartiauxDie}+${Math.max(forM,dexM)}','Arts martiaux')">🎲 1${artsMartiauxDie}${fmt(Math.max(forM,dexM))} dégâts</button>
          <div style="font-size:10px;color:var(--text3);margin-top:3px">Action bonus : 1 frappe supplémentaire (sans ki)</div></div>
        </div>
        ${!(p.equip||{}).chest?.name?`<div style="margin-top:8px;padding:6px 10px;background:var(--surface2);border-radius:6px;font-size:11px;color:var(--text3)">🛡 Défense sans armure (sans armure) : CA = 10 + DEX (${fmt(dexM)}) + SAG (${fmt(sagM)}) = <strong style="color:var(--cp)">${10+dexM+sagM}</strong></div>`:''}
      </div>
      ${moineLvl>=2?(()=>{const remaining=(p.combatCharges?.['Ki']!==undefined)?p.combatCharges['Ki']:kiMax;return`<div style="border-top:1px solid var(--border);padding-top:10px;margin-bottom:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">☯ Points de ki — ${kiMax} / récup. repos court</div><div style="font-size:11px;color:var(--text3);margin-bottom:8px">Points dépensés pour activer des techniques de moine. Coût : 1 à plusieurs ki selon la technique.</div><div style="display:flex;gap:4px;flex-wrap:wrap;margin-bottom:6px">${Array.from({length:kiMax},(_,ki)=>`<span class="slot-bubble${ki<remaining?'':' used'}" onclick="toggleKi(${ki},${kiMax})" style="cursor:pointer" title="${ki<remaining?'Cliquer pour dépenser 1 ki':'ki dépensé'}"></span>`).join('')}</div><div style="display:flex;align-items:center;gap:8px"><span style="font-size:11px;color:var(--text3)">${remaining}/${kiMax} disponibles</span><button class="btn bsm" onclick="P().combatCharges=P().combatCharges||{};P().combatCharges['Ki']=${kiMax};_markUnsaved();render()">↺ Repos court</button></div></div>`;})():''}
      <div style="border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:8px">Techniques disponibles</div>
        ${moineLvl>=2?`<div style="padding:7px 10px;background:var(--surface2);border-radius:6px;margin-bottom:6px"><div style="font-size:12px;font-weight:600">🌊 Déluge de coups <span style="font-size:10px;color:var(--cp);margin-left:4px">1 ki</span></div><div style="font-size:11px;color:var(--text3);margin-top:2px">Action bonus : effectue 2 frappes à mains nues supplémentaires après l'action Attaquer.</div></div>`:''}
        ${moineLvl>=2?`<div style="padding:7px 10px;background:var(--surface2);border-radius:6px;margin-bottom:6px"><div style="font-size:12px;font-weight:600">💨 Pas du vent <span style="font-size:10px;color:var(--cp);margin-left:4px">1 ki</span></div><div style="font-size:11px;color:var(--text3);margin-top:2px">Action bonus : Se désengager OU Esquiver. Réaction : Se dresser quand une créature rate une attaque contre toi.</div></div>`:''}
        ${moineLvl>=3?`<div style="padding:7px 10px;background:var(--surface2);border-radius:6px;margin-bottom:6px"><div style="font-size:12px;font-weight:600">🛡 Parade de projectiles <span style="font-size:10px;color:var(--cp);margin-left:4px">1 ki (réaction)</span></div><div style="font-size:11px;color:var(--text3);margin-top:2px">Réaction : réduis les dégâts d'une attaque à distance de 1d10 + DEX + niveau. Si tu ramènes à 0, tu peux relancer le projectile.</div></div>`:''}
        ${moineLvl<2?`<div style="font-size:11px;color:var(--text3);font-style:italic;padding:4px 0">Ki et techniques disponibles à partir du niveau 2.</div>`:''}
        ${moineLvl>=5?`<div style="padding:7px 10px;background:var(--surface2);border-radius:6px;margin-bottom:6px"><div style="font-size:12px;font-weight:600">⚡ Frappe étourdissante <span style="font-size:10px;color:var(--cp);margin-left:4px">1 ki</span></div><div style="font-size:11px;color:var(--text3);margin-top:2px">Lors d'une attaque qui touche : la cible doit réussir un JS CON (DD ${8+pb(lvl)+Math.max(forM,dexM)}) ou est étourdie jusqu'à la fin de ton prochain tour.</div></div>`:''}
        ${moineLvl>=5?`<div style="padding:7px 10px;background:var(--surface2);border-radius:6px;margin-bottom:6px"><div style="font-size:12px;font-weight:600">🏹 Déflexion de projectiles <span style="font-size:10px;color:var(--text3);margin-left:4px">niv.5</span></div><div style="font-size:11px;color:var(--text3);margin-top:2px">Si tu pares à 0, tu peux relancer le projectile (portée 18m, att. DEX, dégâts Arts martiaux + DEX).</div></div>`:''}
        ${moineLvl>=9?`<div style="padding:7px 10px;background:var(--surface2);border-radius:6px;margin-bottom:6px"><div style="font-size:12px;font-weight:600">⚡ Pas comme l'éclair <span style="font-size:10px;color:var(--cp);margin-left:4px">2 ki</span></div><div style="font-size:11px;color:var(--text3);margin-top:2px">Action bonus : téléporte-toi jusqu'à 18m vers un espace libre que tu vois.</div></div>`:''}
        ${moineLvl>=11?`<div style="padding:7px 10px;background:var(--surface2);border-radius:6px;margin-bottom:6px"><div style="font-size:12px;font-weight:600">💫 Frappe des quatre vents <span style="font-size:10px;color:var(--cp);margin-left:4px">3 ki</span></div><div style="font-size:11px;color:var(--text3);margin-top:2px">Tous les ennemis dans un rayon de 4,5m doivent réussir un JS DEX (DD ${8+pb(lvl)+Math.max(forM,dexM)}) ou subir 3 × ${artsMartiauxDie} dégâts contondants.</div><button class="btn bsm" style="margin-top:4px" onclick="rollCustomDmg('3${artsMartiauxDie}','Frappe des quatre vents')">🎲 3${artsMartiauxDie}</button></div>`:''}
        ${isPaume&&moineLvl>=17?`<div style="padding:7px 10px;background:var(--surface2);border-radius:6px;margin-bottom:6px"><div style="font-size:12px;font-weight:600">☠ Frappe des vibrations <span style="font-size:10px;color:var(--cp);margin-left:4px">3 ki</span></div><div style="font-size:11px;color:var(--text3);margin-top:2px">Lors d'une attaque : paralyse (JS CON DD ${8+pb(lvl)+Math.max(forM,dexM)}) ou arrêt du cœur si la cible est déjà paralysée (JS CON ou tombe à 0 PV).</div></div>`:''}
        ${moineLvl>=18?`<div style="padding:7px 10px;background:var(--surface2);border-radius:6px;margin-bottom:6px"><div style="font-size:12px;font-weight:600">👻 Corps vide <span style="font-size:10px;color:var(--cp);margin-left:4px">4 ki</span></div><div style="font-size:11px;color:var(--text3);margin-top:2px">Action : invisible 1 minute, résistance à tous les dégâts sauf force psychique.</div></div>`:''}
      </div>
      ${isPaume&&moineLvl>=3?`<div style="margin-top:12px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:6px">🥋 Voie de la paume</div><div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Technique de la paume (niv.3) — Quand tu touches avec Déluge de coups : pousser 4,5m / faire tomber / priver de réaction (au choix)</div>${moineLvl>=6?(()=>{const ppUsed=!!(p.combatCharges||{})['PlénitudePhysiqueUsed'];return`<div style="padding:6px 8px;background:${ppUsed?'rgba(200,168,75,.08)':'var(--surface2)'};border:1px solid ${ppUsed?'var(--cp)':'var(--border)'};border-radius:6px;margin-bottom:4px"><div style="font-size:11px;font-weight:600;color:var(--text2)">Plénitude physique (niv.6) — 1×/repos long</div><div style="font-size:10px;color:var(--text3);margin:2px 0">Action : récupère ${moineLvl*3} PV (niveau × 3)</div>${ppUsed?`<button class="btn bsm" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};delete p.combatCharges['PlénitudePhysiqueUsed'];saveAll();render();})()">↺ Repos long</button>`:`<button class="btn bsm" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};p.combatCharges['PlénitudePhysiqueUsed']=true;p.hp=Math.min(p.hpMax||(p.hp||0),p.hp+${moineLvl*3});saveAll();render();showToast('💚 +${moineLvl*3} PV (Plénitude physique)');})()">⚡ Soigner (+${moineLvl*3} PV)</button>`}</div>`;})():''}${moineLvl>=11?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px">Tranquillité (niv.11) — Après un repos long, bénéfice de Sanctuaire (DD ${8+pb(moineLvl)+sagM}) jusqu'au prochain tour de combat</div>`:''}</div>`:''}
      ${isOmbre&&moineLvl>=3?`<div style="margin-top:12px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:6px">🌑 Voie de l'ombre</div><div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Arts des ombres (niv.3) — 2 ki : lancer ténèbres, vision dans le noir, passage sans trace ou silence. Illusion mineure gratuite en tout temps.</div>${moineLvl>=6?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Foulée d'ombre (niv.6) — Action bonus : téléportation 18m dans un espace en pénombre ou ténèbres. Avantage sur la prochaine attaque.</div>`:''} ${moineLvl>=11?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Linceul d'ombre (niv.11) — Action : devenir invisible en pénombre/ténèbres (jusqu'au début de ton prochain tour)</div>`:''} ${moineLvl>=17?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px">Opportuniste (niv.17) — Réaction : quand une créature à 1,5m est touchée par un allié, tu peux faire 1 attaque contre elle</div>`:''}</div>`:''}
      ${isQE&&moineLvl>=3?`<div style="margin-top:12px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:6px">🌊 Voie des quatre éléments</div><div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Disciple des éléments — Lien élémentaire + 1 discipline au niv.3 (nouvelles aux niv.6/11/17). Chaque discipline coûte 2 à 6 pts de ki selon son niveau.</div><div style="font-size:11px;color:var(--text3)">DD des sorts : ${8+pb(moineLvl)+sagM}. Utilise les pts de ki communs.</div></div>`:''}
      ${moineLvl>=10?`<div style="margin-top:8px;padding:6px 10px;background:var(--surface2);border-radius:6px;font-size:11px;color:var(--text3)">🌿 <strong>Pureté du corps</strong> (niv.10) : Immunité aux maladies et aux poisons.</div>`:''}
      ${moineLvl>=13?`<div style="margin-top:6px;padding:6px 10px;background:var(--surface2);border-radius:6px;font-size:11px;color:var(--text3)">💎 <strong>Âme de diamant</strong> (niv.13) : Maîtrise de tous les jets de sauvegarde.</div>`:''}
      ${moineLvl>=15?`<div style="margin-top:6px;padding:6px 10px;background:var(--surface2);border-radius:6px;font-size:11px;color:var(--text3)">🧘 <strong>Silence éternel</strong> (niv.15) : Immunité aux états charmé et effrayé.</div>`:''}
      ${moineLvl>=20?`<div style="margin-top:6px;padding:6px 10px;background:var(--surface2);border-radius:6px;font-size:11px;color:var(--text3)">✨ <strong>Perfection du soi</strong> (niv.20) : Si tu tires un 9 ou moins à un jet de caractéristique FOR ou DEX, tu obtiens 10.</div>`:''}
    </div>`);
}

function toggleKi(idx,max){const p=P();if(!p.combatCharges)p.combatCharges={};const cur=p.combatCharges['Ki']!==undefined?p.combatCharges['Ki']:max;p.combatCharges['Ki']=idx<cur?idx:Math.min(max,idx+1);_markUnsaved();render();}
