// PALADIN — Panneau de combat + actions
// ═══════════════════════════════════════

function renderPaladin(p) {
  const wsC = p.wildshape;
  const paladinLvl = ((p.classes||[]).find(c=>c.name==='Paladin')||{}).level||0;
  if (!paladinLvl || wsC?.active) return '';
  const lvl = totalLevel(p);
  const chaM = mod(p.abilities[5]);
  const slots = calcSpellSlots(p);
  const slotsUsed = p.spellSlotsUsed||[];
  const paladinPath = (p.features||[]).find(f=>['Serment de dévotion','Serment des anciens','Serment de vengeance'].includes(f.name));
  const isDevot = paladinPath?.name==='Serment de dévotion';
  const isAnciens = paladinPath?.name==='Serment des anciens';
  const isVengeance = paladinPath?.name==='Serment de vengeance';

  return cs('cs-paladin',`<div class="panel mb10"><div class="pt" style="display:flex;align-items:center;gap:6px"><span class="mj-drag-handle" title="Déplacer">⠿</span>🛡 Paladin — Capacités</div>
    ${slots&&slots.length>0?(()=>{const maxSmite=Math.min(5,slots.length);return`<div style="margin-bottom:14px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">⚡ Châtiment divin</div><div style="font-size:11px;color:var(--text3);margin-bottom:8px">Dépense un emplacement après avoir touché : +2d8 radiants au niv.1, +1d8/niveau supplémentaire (max 5d8). +1d8 bonus vs morts-vivants/fiélons.</div><div style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:8px">${Array.from({length:maxSmite},(_,n)=>{const slotLvl=n+1;const remaining=Math.max(0,(slots[n]||0)-(slotsUsed[n]||0));const dice=Math.min(5,slotLvl+1);return`<button class="btn bsm${remaining<=0?' disabled':''}" ${remaining<=0?'disabled':''} onclick="rollChatimentDivin(${slotLvl})" style="${remaining<=0?'opacity:.4':''}">Niv.${slotLvl} — ${dice}d8 <span style="font-size:9px;color:var(--text3)">(${remaining} slot${remaining>1?'s':''})</span></button>`;}).join('')}</div><label style="font-size:11px;color:var(--text3);display:flex;align-items:center;gap:6px"><input type="checkbox" id="smiteCritCheck"> Coup critique (dés × 2)</label></div>`;})():''}
    ${paladinLvl>=3?(()=>{const cdUsed=(p.combatCharges||{})['Conduit divin']!==undefined?p.combatCharges['Conduit divin']:1;return`<div style="margin-bottom:14px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">✝ Conduit divin</div><div style="font-size:11px;color:var(--text3);margin-bottom:8px">${_featDesc('Paladin','Conduit divin')}</div><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><div style="display:flex;gap:4px"><span class="slot-bubble${cdUsed>0?'':' used'}" onclick="useCombatCharge('Conduit divin',1)"></span></div><button class="btn bsm" onclick="recoverCombatCharge('Conduit divin',1)">↺ Repos court</button></div></div>`;})():''}
    <div style="margin-bottom:14px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">🙏 Imposition des mains</div>
      <div style="font-size:11px;color:var(--text3);margin-bottom:8px">${_featDesc('Paladin','Imposition des mains')}</div>
      ${(()=>{const imMax=paladinLvl*5;const imCur=(p.combatCharges||{})['ImpositionMains']!==undefined?p.combatCharges['ImpositionMains']:imMax;const imPct=imMax>0?Math.round(imCur/imMax*100):0;return`<div style="display:flex;justify-content:space-between;font-size:11px;color:var(--text3);margin-bottom:4px"><span>Réservoir</span><span style="font-weight:700;color:${imCur<=0?'#e53935':'var(--cp)'}">${imCur} / ${imMax} PV</span></div><div style="height:8px;background:var(--surface2);border-radius:4px;overflow:hidden;margin-bottom:10px"><div style="height:100%;width:${imPct}%;background:var(--cp);border-radius:4px"></div></div><div style="display:flex;gap:6px;flex-wrap:wrap"><button class="btn bsm" onclick="_spendImpositionMains(1)" ${imCur<1?'disabled':''}>−1 PV</button><button class="btn bsm" onclick="_spendImpositionMains(5)" ${imCur<5?'disabled':''}>−5 PV</button><button class="btn bsm" onclick="_spendImpositionMains(10)" ${imCur<10?'disabled':''}>−10 PV</button><button class="btn bsm" onclick="_restoreImpositionMains()">↺ Repos long</button></div>`;})()}
    </div>
    ${paladinLvl>=6?`<div style="margin-bottom:${paladinLvl>=10?'14':'0'}px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">🛡 Aura de protection</div><div style="font-size:11px;color:var(--text3)">${_featDesc('Paladin','Aura de protection')}</div><div style="font-size:13px;font-weight:700;color:var(--cp);margin-top:6px">+${Math.max(1,chaM)} à tous les JS des alliés proches</div></div>`:''}
    ${paladinLvl>=10?`<div style="margin-bottom:${paladinLvl>=20?'14':'0'}px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">💛 Aura de courage</div><div style="font-size:11px;color:var(--text3)">${_featDesc('Paladin','Aura de courage')}</div></div>`:''}
    ${paladinLvl>=20?(()=>{const fsUsed=(p.combatCharges||{})['FormeSacree']!==undefined?p.combatCharges['FormeSacree']:1;return`<div><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">👼 Forme sacrée</div><div style="font-size:11px;color:var(--text3);margin-bottom:8px">${_featDesc('Paladin','Forme sacrée')}</div><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><span class="slot-bubble${fsUsed>0?'':' used'}" onclick="useCombatCharge('FormeSacree',1)"></span><button class="btn bsm" onclick="recoverCombatCharge('FormeSacree',1)">↺ Repos long</button></div></div>`;})():''}
    ${(()=>{const sdMax=Math.max(1,1+chaM);const sdCur=(p.combatCharges||{})['SensDivin']!==undefined?p.combatCharges['SensDivin']:sdMax;return`<div style="margin-top:10px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">👁 Sens divin</div><div style="font-size:11px;color:var(--text3);margin-bottom:6px">Action bonus : détecter célestes/fiélons/morts-vivants à 18m pendant 1 tour. ${sdMax}/repos long.</div><div style="display:flex;align-items:center;gap:6px;flex-wrap:wrap"><div style="display:flex;gap:4px">${Array.from({length:sdMax},(_,i)=>`<span class="slot-bubble${i<sdCur?'':' used'}" onclick="useCombatCharge('SensDivin',${sdMax})"></span>`).join('')}</div><span style="font-size:10px;color:var(--text3)">${sdCur}/${sdMax}</span><button class="btn bsm" onclick="recoverCombatCharge('SensDivin',${sdMax})">↺ Repos long</button></div></div>`;})()}
    ${paladinLvl>=3?`<div style="margin-top:6px;padding:5px 8px;background:var(--surface2);border-radius:6px;font-size:11px;color:var(--text2)">🏥 Santé divine (niv.3) — Immunité aux maladies</div>`:''}
    ${paladinLvl>=14?(()=>{const cpMax=Math.max(1,chaM);const cpCur=(p.combatCharges||{})['ContactPurifiant']!==undefined?p.combatCharges['ContactPurifiant']:cpMax;return`<div style="margin-top:6px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:4px">✋ Contact purifiant (niv.14)</div><div style="font-size:11px;color:var(--text3);margin-bottom:6px">Action : toucher une créature → mettre fin à 1 sort. ${cpMax}/repos long.</div><div style="display:flex;align-items:center;gap:6px;flex-wrap:wrap"><div style="display:flex;gap:4px">${Array.from({length:cpMax},(_,i)=>`<span class="slot-bubble${i<cpCur?'':' used'}" onclick="useCombatCharge('ContactPurifiant',${cpMax})"></span>`).join('')}</div><span style="font-size:10px;color:var(--text3)">${cpCur}/${cpMax}</span><button class="btn bsm" onclick="recoverCombatCharge('ContactPurifiant',${cpMax})">↺ Repos long</button></div></div>`;})():''}
    ${paladinLvl>=18?`<div style="margin-top:6px;padding:5px 8px;background:var(--surface2);border-radius:6px;font-size:11px;color:var(--text2)">📡 Amélioration des auras (niv.18) — Rayon des auras : 3m → 9m</div>`:''}
    ${isDevot&&paladinLvl>=3?`<div style="margin-top:10px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:6px">⚔ Serment de dévotion</div><div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Conduit : Arme sacrée (action : +CHA aux attaques, lumière 1 min) / Renvoi des impies (JS SAG DD ${8+pb(paladinLvl)+chaM} ou morts-vivants/fiélons renvoyés)</div>${paladinLvl>=7?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Aura de dévotion (niv.7) — Immunité aux charmes pour toi et tes alliés dans l'aura</div>`:''} ${paladinLvl>=15?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Pureté de l'esprit (niv.15) — Sous les effets permanents de Protection contre le mal et le bien</div>`:''} ${paladinLvl>=20?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px">Nimbe sacré (niv.20) — Lumière 9m, 10 radiants/début tour ennemi, avantage JS vs fiélons/morts-vivants</div>`:''}</div>`:''}
    ${isAnciens&&paladinLvl>=3?(()=>{const siUsed=!!((p.combatCharges||{})['SentinelleImmortelleUsed']);return`<div style="margin-top:10px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:6px">🌿 Serment des anciens</div><div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Conduit : Courroux de la nature (vignes : Entravé, JS FOR/DEX) / Renvoi des infidèles (fées/fiélons : renvoyés)</div>${paladinLvl>=7?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Aura de garde (niv.7) — Toi et alliés dans l'aura : résistance aux dégâts des sorts</div>`:''} ${paladinLvl>=15?`<div style="padding:5px 8px;background:${siUsed?'rgba(200,168,75,.1)':'var(--surface2)'};border:1px solid ${siUsed?'var(--cp)':'var(--border)'};border-radius:6px;margin-bottom:4px"><div style="font-size:11px;font-weight:600">Sentinelle immortelle (niv.15) — 1/repos long</div><div style="font-size:10px;color:var(--text3);margin:2px 0">Si tu tombes à 0 PV, tu restes à 1 PV à la place</div><div style="display:flex;gap:4px;margin-top:4px"><span class="slot-bubble${siUsed?' used':''}" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};p.combatCharges['SentinelleImmortelleUsed']=!p.combatCharges['SentinelleImmortelleUsed'];saveAll();render();})()"></span><button class="btn bsm" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};delete p.combatCharges['SentinelleImmortelleUsed'];saveAll();render();})()">↺ Repos long</button></div></div>`:''} ${paladinLvl>=20?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px">Champion antique (niv.20) — 1 min : soins 10 PV/tour, sorts en action bonus, désavantage JS ennemis à 3m</div>`:''}</div>`;})():''}
    ${isVengeance&&paladinLvl>=3?(()=>{const voeuUsed=!!((p.combatCharges||{})['VoeuHostiliteUsed']);return`<div style="margin-top:10px;border-top:1px solid var(--border);padding-top:10px"><div style="font-size:12px;font-weight:600;color:var(--cp);margin-bottom:6px">🗡 Serment de vengeance</div><div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Conduit : Conspuer l'ennemi (JS SAG DD ${8+pb(paladinLvl)+chaM} : effrayé ou vitesse ÷2) / Vœu d'hostilité (action bonus : avantage vs 1 cible 1 min)</div>${paladinLvl>=7?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Vengeur implacable (niv.7) — Attaque d'opportunité réussie → déplacement ½ vitesse en réaction</div>`:''} ${paladinLvl>=15?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px;margin-bottom:4px">Âme vengeresse (niv.15) — Réaction : attaquer la cible du Vœu quand elle attaque une autre créature</div>`:''} ${paladinLvl>=20?`<div style="font-size:11px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:6px">Ange de la vengeance (niv.20) — 1h : vol 18m, aura peur 9m, avantage vs créatures effrayées</div>`:''}</div>`;})():''}
  </div>`);
}

function rollChatimentDivin(slotLvl){
  const p=P();const isCrit=document.getElementById('smiteCritCheck')?.checked||false;
  const dice=Math.min(5,slotLvl+1);const numDice=isCrit?dice*2:dice;
  const rolls=Array.from({length:numDice},()=>Math.ceil(Math.random()*8));
  const total=rolls.reduce((s,v)=>s+v,0);
  if(!p.spellSlotsUsed)p.spellSlotsUsed=[];
  while(p.spellSlotsUsed.length<slotLvl)p.spellSlotsUsed.push(0);
  p.spellSlotsUsed[slotLvl-1]=(p.spellSlotsUsed[slotLvl-1]||0)+1;
  _markUnsaved();
  showToast(`⚡ Châtiment divin — Niv.${slotLvl} : ${rolls.join('+')} = <strong style="color:#ffd54f;font-size:15px">${total}</strong> dégâts radiants${isCrit?' 🎉 CRITIQUE':''}`,4000);
  render();
}

function _spendImpositionMains(amount){const p=P();const mx=((p.classes||[]).find(c=>c.name==='Paladin')||{}).level*5||0;if(!p.combatCharges)p.combatCharges={};const cur=p.combatCharges['ImpositionMains']!==undefined?p.combatCharges['ImpositionMains']:mx;if(cur<amount){showToast('❌ Pas assez de PV dans le réservoir !');return;}p.combatCharges['ImpositionMains']=cur-amount;render();}
function _restoreImpositionMains(){const p=P();const mx=((p.classes||[]).find(c=>c.name==='Paladin')||{}).level*5||0;if(!p.combatCharges)p.combatCharges={};p.combatCharges['ImpositionMains']=mx;render();}
