// ROUBLARD — Panneau de combat
// ═══════════════════════════════════════

function renderRoublard(p) {
  const wsC = p.wildshape;
  const roublardLvl = ((p.classes||[]).find(c=>c.name==='Roublard')||{}).level||0;
  if (!roublardLvl || wsC?.active) return '';
  const lvl = totalLevel(p);
  const dexM = mod(p.abilities[1]);
  const intM = mod(p.abilities[3]);
  const roublardPath = (p.features||[]).find(f=>['Voleur','Escroc arcanique','Assassin','Conspirateur'].includes(f.name));
  const isAssassin = roublardPath?.name==='Assassin';
  const isVoleur = roublardPath?.name==='Voleur';
  const isEscrocArc = roublardPath?.name==='Escroc arcanique';
  const isCons = roublardPath?.name==='Conspirateur';
  const snkDice = Math.ceil(roublardLvl/2);

  return cs('cs-roublard',`<div class="panel mb10"><div class="pt" style="display:flex;align-items:center;gap:6px"><span class="mj-drag-handle" title="Déplacer">⠿</span>🗡 Roublard — Capacités</div>
    <div style="margin-bottom:14px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:4px">🎯 Attaque sournoise</div><div style="font-size:13px;color:var(--text3);margin-bottom:8px">1 fois par tour. Si avantage OU allié adjacent à la cible (pas de désavantage). Arme de finesse ou à distance. Ajoute ${snkDice}d6 aux dégâts.</div><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><div class="sb hi" style="padding:6px 14px;flex-shrink:0"><div class="sn">Dés</div><div style="font-size:15px;font-weight:700;color:var(--cp)">${snkDice}d6</div></div><button class="btn bsm" onclick="rollCustomDmg('${snkDice}d6','Attaque sournoise')">🎲 ${snkDice}d6</button></div></div>
    ${roublardLvl>=2?`<div style="margin-bottom:8px;padding:8px;background:var(--surface2);border-radius:2px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:2px">⚡ Ruse (niv.2) <span style="font-size:12px;color:var(--cp)">🔸</span></div><div style="font-size:13px;color:var(--text3)">Action bonus chaque tour : Foncer (vitesse ×2), Se désengager (pas d'attaque d'opportunité) ou Se cacher (jet de Discrétion).</div></div>`:''}
    ${roublardLvl>=5?`<div style="margin-bottom:8px;padding:8px;background:var(--surface2);border-radius:2px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:2px">🛡 Esquive instinctive (niv.5) <span style="font-size:12px;color:var(--cp)">↪</span></div><div style="font-size:13px;color:var(--text3)">Réaction quand un attaquant que tu vois te touche : réduire de moitié les dégâts reçus.</div></div>`:''}
    ${roublardLvl>=7?`<div style="margin-bottom:8px;padding:8px;background:var(--surface2);border-radius:2px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:2px">💨 Esquive totale (niv.7)</div><div style="font-size:13px;color:var(--text3)">Si tu réussis un JS DEX contre un effet qui inflige la moitié des dégâts, tu ne subis aucun dégât. Si tu rates, seulement la moitié.</div></div>`:''}
    ${roublardLvl>=11?`<div style="margin-bottom:8px;padding:8px;background:var(--surface2);border-radius:2px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:2px">💎 Talent fiable (niv.11)</div><div style="font-size:13px;color:var(--text3)">Tout jet de compétence maîtrisée : un résultat du d20 de 9 ou moins compte automatiquement comme 10.</div></div>`:''}
    ${roublardLvl>=14?`<div style="margin-bottom:8px;padding:8px;background:var(--surface2);border-radius:2px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:2px">👁 Perception aveugle (niv.14)</div><div style="font-size:13px;color:var(--text3)">Si tu peux entendre, tu connais la position de toute créature cachée ou invisible à 3m ou moins.</div></div>`:''}
    ${roublardLvl>=15?`<div style="margin-bottom:8px;padding:8px;background:var(--surface2);border-radius:2px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:2px">🧠 Esprit fuyant (niv.15)</div><div style="font-size:13px;color:var(--text3)">Tu gagnes la maîtrise aux jets de sauvegarde de Sagesse.</div></div>`:''}
    ${roublardLvl>=18?`<div style="margin-bottom:8px;padding:8px;background:var(--surface2);border-radius:2px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:2px">👻 Insaisissable (niv.18)</div><div style="font-size:13px;color:var(--text3)">Aucun jet d'attaque n'a d'avantage contre toi tant que tu n'es pas incapable d'agir.</div></div>`:''}
    ${roublardLvl>=20?(()=>{const ccUsed=!!((p.combatCharges||{})['CoupDeChanceUsed']);return`<div style="margin-bottom:8px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:4px">🍀 Coup de chance (niv.20) — 1/repos court</div><div style="font-size:13px;color:var(--text3);margin-bottom:6px">Si ton attaque rate : transformer en succès. Si tu rates un jet de caractéristique : traiter le d20 comme 20.</div><div style="display:flex;align-items:center;gap:6px"><span class="slot-bubble${ccUsed?' used':''}" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};p.combatCharges['CoupDeChanceUsed']=!p.combatCharges['CoupDeChanceUsed'];saveAll();render();})()"></span><button class="btn bsm" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};delete p.combatCharges['CoupDeChanceUsed'];saveAll();render();})()">↺ Repos court</button></div></div>`;})():''}
    ${roublardLvl>=3?(()=>{if(!roublardPath)return'';const archIcon=isAssassin?'🗡':isVoleur?'🎭':isEscrocArc?'🔮':'🕵';let html=`<div style="border-top:1px solid var(--border);padding-top:10px;margin-top:8px"><div style="font-size:13px;font-weight:600;color:var(--cp);margin-bottom:6px">${archIcon} ${roublardPath.name}</div>`;
    if(isAssassin){const _am=(p.combatCharges||{})['AssassinatReady']||'';const _fmDD=8+pb(lvl)+dexM;
    html+=`<div style="padding:7px 10px;background:${_am?'rgba(156,39,176,.08)':'var(--surface2)'};border:1px solid ${_am?'rgba(156,39,176,.4)':'var(--border)'};border-radius:2px;margin-bottom:4px">
      <div style="font-size:13px;font-weight:600;margin-bottom:4px">🎯 Assassinat — armer l'attaque</div>
      <div style="display:flex;gap:4px;flex-wrap:wrap;margin-bottom:4px">
        <button class="btn bsm${_am==='adv'?' bac':''}" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};p.combatCharges['AssassinatReady']=p.combatCharges['AssassinatReady']==='adv'?'':'adv';saveAll();render();})()">⚔ Cible n'a pas agi (avantage)</button>
        <button class="btn bsm${_am==='surprise'?' bac':''}" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};p.combatCharges['AssassinatReady']=p.combatCharges['AssassinatReady']==='surprise'?'':'surprise';saveAll();render();})()">💀 Cible SURPRISE (avantage + critique auto)</button>
        ${_am?`<button class="btn bsm" onclick="(()=>{const p=P();if(!p.combatCharges)p.combatCharges={};delete p.combatCharges['AssassinatReady'];saveAll();render();})()">✕ Désarmer</button>`:''}
      </div>
      <div style="font-size:12px;color:var(--text3)">${_am==='surprise'?`💀 Armé : tes boutons d'attaque ont l'avantage et toute touche est un CRITIQUE automatique.${roublardLvl>=17?` 🗡 Frappe meurtrière : la cible doit réussir un JS CON DD ${_fmDD} ou subir les dégâts DOUBLÉS (calculé sur le jet).`:''} Pense à désarmer après le 1er round.`:_am==='adv'?`⚔ Armé : tes boutons d'attaque ont l'avantage contre les créatures qui n'ont pas encore agi. Pense à désarmer ensuite.`:"Arme le mode avant d'attaquer : les boutons d'attaque appliquent l'avantage (et le critique automatique sur cible surprise)."}</div>
    </div>`;
    html+=`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Maîtrises supplémentaires (niv.3) — Kit de déguisement et kit d'empoisonneur.</div><div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Assassinat (niv.3) — Avantage contre toute créature n'ayant pas encore agi. Coup critique automatique si la cible est surprise.</div>${roublardLvl>=9?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Expert en infiltration (niv.9) — Créer de fausses identités (1 semaine, 25 po). Elles passent pour réelles jusqu'à preuve du contraire.</div>`:''}${roublardLvl>=13?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Imposteur (niv.13) — Dupliquer parfaitement la voix, l'écriture et les manières d'une personne étudiée 3h.</div>`:''}${roublardLvl>=17?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px">Frappe meurtrière (niv.17) — Touche sur une cible surprise : JS CON DD ${8+pb(roublardLvl)+dexM} ou les dégâts de l'attaque sont doublés.</div>`:''}`;}
    if(isVoleur){html+=`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Mains lestes (niv.3) — Action bonus (via Ruse) : Escamotage, crocheter serrure/piège, ou Utiliser un objet.</div><div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Monte-en-l'air (niv.3) — Escalade sans surcoût de mouvement. Saut en longueur +DEX×30cm.</div>${roublardLvl>=9?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Discrétion suprême (niv.9) — Avantage à Discrétion si tu ne te déplaces pas de plus de la moitié de ta vitesse.</div>`:''}${roublardLvl>=13?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Utilisation d'objets magiques (niv.13) — Ignorer conditions de classe/race/niveau pour les objets magiques.</div>`:''}${roublardLvl>=17?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px">Réflexes de voleur (niv.17) — Deux tours au 1er round : initiative normale, puis initiative−10.</div>`:''}`;}
    if(isEscrocArc){html+=`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Incantation (niv.3) — Sorts INT (enchantement/illusion). DD ${8+pb(roublardLvl)+intM} · Bonus attaque +${pb(roublardLvl)+intM}.</div><div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Escamotage et main de mage (niv.3) — Main de mage invisible gratuite, contrôlée via action bonus (Ruse).</div>${roublardLvl>=9?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Embuscade magique (niv.9) — Si caché quand tu lances un sort sur une cible : elle a désavantage à son JS.</div>`:''}${roublardLvl>=13?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Escroc polyvalent (niv.13) — Action bonus : main de mage distrait une créature à 1,5m → avantage à tes attaques contre elle.</div>`:''}${roublardLvl>=17?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px">Voleur de sort (niv.17) — Réaction contre un sort qui te cible : JS du lanceur ou tu voles le sort 8h.</div>`:''}`;}
    if(isCons){html+=`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Maître des intrigues (niv.3) — Maîtrise kit de déguisement, kit de contrefaçon, un jeu + 2 langues. Imiter parfaitement une voix/un accent entendu 1 min.</div><div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Maître des tactiques (niv.3) — Action Aider en action bonus, portée 9m si la cible peut te voir ou t'entendre.</div>${roublardLvl>=9?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Manipulateur perspicace (niv.9) — 1 min d'interaction : comparer INT/SAG/CHA/niveau de classe avec la cible.</div>`:''}${roublardLvl>=13?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px;margin-bottom:4px">Redirection (niv.13) — Réaction : détourner une attaque te ciblant vers une créature à 1,5m qui t'offre un abri.</div>`:''}${roublardLvl>=17?`<div style="font-size:13px;color:var(--text2);padding:5px 8px;background:var(--surface2);border-radius:2px">Âme de la duperie (niv.17) — Pensées illisibles par télépathie (fausses pensées à la place). La magie de vérité te voit toujours véridique ; tu peux mentir dans les langues que tu connais.</div>`:''}`;}
    html+='</div>';return html;})():''}
  </div>`);
}
